import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Footer from "~/components/Footer";
import Header from "~/components/Header";
import HomeHero from "~/components/HomeHero";
import styles from "~/styles/index.module.css";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
    const [firstRandomColor, setFirstRandomColor] = useState<string>("");
    const [secondRandomColor, setSecondRandomColor] = useState<string>("");
    const [darkText, setDarkText] = useState<string>("text-zinc-200");

    const generateRandomDarkColor = () => {
        const randomRed = Math.floor(Math.random() * 100) + 30;
        const randomGreen = Math.floor(Math.random() * 100) + 30;
        const randomBlue = Math.floor(Math.random() * 100) + 30;
        return rgbToHex(randomRed, randomGreen, randomBlue);
    }

    const toRGB = (color: any) => {
        const { style } = new Option();
        style.color = color;
        return style.color;
    }

    const setRandomGradientBackground = () => {
        const [colorOne, colorTwo] = [generateRandomDarkColor(), generateRandomDarkColor()];
        setFirstRandomColor((colorOne));
        setSecondRandomColor((colorTwo));
        document.body.style.background = `linear-gradient(90deg, ${colorOne} 0%, ${colorTwo} 100%)`;
    };

    const componentToHex = (c: any) => {
        var hex = c.toString(16);
        return hex.length == 1 ? "0" + hex : hex;
    }

    const rgbToHex = (r: any, g: any, b: any) => {
        return "#" + componentToHex(r) + componentToHex(g) + componentToHex(b);
    }
    useEffect(() => {
        setRandomGradientBackground();
    }, []);

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${darkText} ${styles.main_container} h-screen flex flex-col`}>
                <Header />
                <div className="flex-grow">
                    <HomeHero />
                </div>
                <Footer />
            </main>
        </>
    );
};

export default Home;
